# Generated by Django 3.2.25 on 2024-06-29 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, null=True)),
                ('last_name', models.CharField(max_length=30, null=True)),
                ('email', models.EmailField(max_length=30, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('login_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prdct.login1')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prdct_name', models.CharField(max_length=30, null=True)),
                ('price', models.IntegerField(null=True)),
                ('category', models.CharField(max_length=30, null=True)),
                ('login_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prdct.login1')),
            ],
        ),
    ]
