# Generated by Django 3.2.25 on 2024-06-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prdct', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
