# Generated by Django 3.2.25 on 2024-06-29 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prdct', '0002_auto_20240629_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='login_id',
        ),
        migrations.RemoveField(
            model_name='register',
            name='login_id',
        ),
        migrations.DeleteModel(
            name='Login1',
        ),
    ]
