# Generated by Django 3.2.19 on 2024-07-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prdct', '0003_auto_20240629_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
