# Generated by Django 3.2.19 on 2024-07-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prdct', '0004_alter_register_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='descriprion',
        ),
    ]
